algoritmo "EMPREGO"
// Disciplina: [Linguagem e Lógica de Programação]

var
   SALARIO: REAL

inicio
ESCREVA ( "Digite o salário: ")
LEIA (SALARIO)
     //condicional Simples
SE ( SALARIO <= 2000) ENTAO
     ESCREVA ( "Candidato selecionado para primeira fase da condicional SIMPLES")
SENAO //resultado falso
     ESCREVA ( "Candidato NÃO PREENCHEU OS REQUISITOS da condicional SIMPLES")

FIMSE

fimalgoritmo
